//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Album.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public abstract class Album {
	private int codigoUnico;
	private Diccionario<String, Figurita> seccionPaisesParticipantes;
	private String premios;
	public Participante Unnamed1;
	public FiguritaTradicional Unnamed2;
	public boolean figuritaEstaPegada(int codigoFigurita) {
	
	}
	
	public Lista<Figurita> pegarFiguritas(Lista<Figurita> figuritas) {
	
	}
	
	public boolean verificarAlbumCompleto() {
	
	}
	
	public boolean verificarArgentinaCompleto() {
	
	}
}
