//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlbumDelMundial.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class AlbumDelMundial {
	private Pais paisesParticipantes;
	private LinkedList<Participante> coleccionistasParticipantes;
	public Participante Unnamed1;
	public Pais Unnamed2;
	public int registrarParticipante(int dni, String nombre, String tipoDeAlbum) {
	
	}
	
	public void comprarFiguritas(int dni) {
	
	}
	
	public void comprarFiguritasTop10(int dni) {
	
	}
	
	public void comprarFiguritasConCodigoPromocional(int dni) {
	
	}
	
	public List<String> pegarFiguritas(int dni) {
	
	}
	
	public boolean llenoAlbum(int dni) {
	
	}
	
	public String aplicarSorteoInstantaneo(int dni) {
	
	}
	
	public int buscarFiguritaRepetida(int dni) {
	
	}
	
	public boolean intercambiar(int dni, int codigoFigurita) {
	
	}
	
	public boolean intercambiarUnaFiguritaRepetida(int dni) {
	
	}
	
	public String darNombre(int dni) {
	
	}
	
	public String darPremio(int dni) {
	
	}
	
	public String listadoDeGanadores() {
	
	}
	
	public List<String> participantesQueCompletaronElPais(String nombrePais) {
	
	}
	
	public List<String> verParticipantesConArgentinaCompletado() {
	
	}
}
