//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlbumExtendido.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class AlbumExtendido extends Album {
	private Diccionario<String, FiguritaTOP10> seccionMejoresJugadores;
	public FiguritaTOP10 Unnamed1;
	public boolean figuritaEstaPegada(int codigoFigurita) {
	
	}
	
	public Lista<Figurita> pegarFiguritas(Lista<Figurita> figuritas) {
	
	}
	
	public boolean verificarAlbumCompleto() {
	
	}
}
