//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlbumWeb.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class AlbumWeb extends Album {
	private int codigoPromocional;
	public int verCodigoPromocional() {
	
	}
}
