//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlbumTradicional.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class AlbumTradicional extends Album {
	private int numeroParaSorteo;
	public int verNumeroParaSorteo() {
	
	}
}
