//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FiguritaTradicional.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class FiguritaTradicional extends Figurita {

	public FiguritaTradicional(Pais paisJugador, double valorBase, String nombreJugador) {
		super(paisJugador, valorBase, nombreJugador);
	}

}
