//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Figurita.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public abstract class Figurita {
	private int numeroIdentificador;
	private double valorBase;
	private String nombreJugador;
	public Participante Unnamed1;
	public double calcularPrecio() {
	
	}
}
