//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FiguritaTOP10.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class FiguritaTOP10 extends Figurita {
	private pais paisBase;
	private int anio;
	private String balonGanado;
	public AlbumExtendido Unnamed1;
	public double calcularPrecio() {
	
	}
}
