//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FiguritaTradicional.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class FiguritaTradicional extends Figurita {
	private Pais pais;
	public Album Unnamed1;
}
