//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pais.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class Pais {
	private String nombre;
	private int ranking;
	public AlbumDelMundial Unnamed1;
	public int verRanking() {
	
	}
	
	public String verNombre() {
	
	}
}
