//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Participante.java
//  @ Date : 23/10/2022
//  @ Author : 
//
//




public class Participante {
	private int dni;
	private String nombreDeUsuario;
	private LinkedList<Figurita> coleccionDeFiguritas;
	private LinkedList<Figurita> figuritasRepetidas;
	private Album album;
	public AlbumDelMundial Unnamed1;
	public Album Unnamed2;
	public Figurita Unnamed3;
	public void agregarFiguritasAColeccion(Lista figuritas) {
	
	}
	
	public List<String> pegarFiguritas() {
	
	}
	
	public boolean verificarAlbumCompleto() {
	
	}
	
	public boolean verificarArgentinaCompleto() {
	
	}
	
	public Figurita buscarFiguritaIntercambiable(Object double valorFigurita) {
	
	}
}
